### PR TITLE
Towards doctest and sphinx

### PR DESCRIPTION
**Pull request by SteffenBrinckmann**
run "make doctest" and "make html" to test both

Artificial trap at end of example to test doctest critically

### CODE REVIEW

**Comment by hakonanes** [comment]
Thanks for this, @SteffenBrinckmann.

I have some points I think we need to get right when introducting checks of our notebooks:
1. The `.rst` files must be created automatically from the notebooks, otherwise we double the maintenance cost.
2. Doctests must be set up to run as checks on Travis (or any other CI platform) so that we ensure any PR changes to the notebooks, or new notebooks, run as expected. I can set this up if necessary.
3. Since the notebooks are in the top directory of the repo, their titles are easily viewable by a new user. For this reason I find the README list unnecessary. I think a direct link to nbviewer rendering of the notebooks (as done for kikuchipy-demos https://github.com/pyxem/kikuchipy-demos) would be the best solution: https://nbviewer.jupyter.org/github/pyxem/orix-demos/

**Comment by SteffenBrinckmann** [comment]
Hey @hakonanes,
1. Agree that would be great. Google tells me there is a nbconvert. Can you set-up such automatic conversion?
2. 100% agree that we need travis, etc. I failed setting something like that up in the past. If you can set it up that would be great. Perhaps travis can use the makefile.
3. I also agree that we can add the notebook in the way you explained to README. Then we can add also the link to the nbviewer you proposed.

My opinion is that we can make small changes to the notebooks and the examples to make them much clearer. I, for one, do not know much about point-space symmetries and do not understand  "0h" symmetry. Also the clustering might not be clear to everybody. Small links to Wiki-pages regarding this symmetry, clustering might help.

My push was only meant to answer Philip's challenge: to show how we can have .rst files that double as doctest and tutorials. It is not meant to be complete / perfect.

**Comment by pc494** [comment]
This discussion is probably best continued in #19.

Could I also ask that the .rst and .html files get pushed up on this PR?

**Comment by hakonanes** [comment]
The final notebook in this repository is now displayed on https://orix.readthedocs.io, and this repository will soon be archived. 

Thank you for showing interest in improving the documentation @SteffenBrinckmann, and for pushing us to improve them.

**Pull request closed without merging**
