### PR TITLE
Add nbviewer badge to README, set up Travis config, pytest nbval

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

See #17 and #19 for initial discussions.

* Add `nbviewer` badge in `README.rst`
* Add Travis CI build badge in `README.rst`
* Add `data` directory with the super-duplex stainless steel (SDSS) ANG used in the `CrystalMap` notebook
* Add Travis config file with Python 3.6-9 builds installing necessary packages and running the script `test_notebooks.sh`
* Add `test_notebooks.sh` bash script which stores an array of the numbers of the notebooks to be tested, finds the corresponding notebook (this means that the file names can be changed, but the notebook number must stay the same), and runs `pytest --nbval notebook.ipynb`
* Add GitHub PR template with reviewer section, reminding us that with every new notebook, if the notebook is to be tested with `pytest --nbval`, (1) the number (e.g. "05") must be added to the array in `test_notebooks.sh`, and (2) the cell outputs must be stored in the `.ipynb` file.

So far only the `CrystalMap` notebook is tested.

To do:
- [x] Make Travis run the builds successfully
Tell Travis to test notebooks as a cron job. (Addressed in #21.)

### CODE REVIEW

**Comment by pc494** [comment]
No rush on these, but a couple of things that jumped out.

- We're not python 3.9 compliant yet, so don't worry if that keeps failing.
- I think you've missed the word "`install`" in the pip statement, although I think we should just install orix and let it handle not the dependencies?

**Comment by hakonanes** [comment]
Thanks @pc494, commented out the 3.9 until we do support it.

I've decided to add a `data/` directory with the ANG file, also removing it from the `.gitignore` list... If you prefer another directory name, and that the directory stays on the list, just say so.

**Comment by pc494** [comment]
`data` is fine, and I'm happy to set up the cron job on travis too.

**Comment by hakonanes** [comment]
For reference, I believe the previous Travis errors were due to what's discussed in this issue: https://github.com/computationalmodelling/nbval/issues/106

**Comment by hakonanes** [comment]
I'm now done, and the tests pass. @pc494, if you could set this up as a cron job, that would be great.

To review this, I suggest:
* looking at how the README and repo structure looks: https://github.com/hakonanes/orix-demos/tree/notebook-checks
* consider whether the PR template is OK
* look at the Travis config file and the test_notebooks.sh bash script if anything is wrong or unclear, so I can add more comments

After that, I think it is ready to be merged.

**Review by pc494 — APPROVED** [review]
Looks great. Will merge.

**Pull request merged**
